version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:80'
    restart: unless-stopped

  # optional dev service for local development using Vite
  dev:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
